services:
  # FastAPI Backend Service
  - type: web
    name: asha-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: neo4j-db
          property: connectionString
      - key: NEO4J_URI
        fromDatabase:
          name: neo4j-db
          property: uri
      - key: NEO4J_USER
        fromDatabase:
          name: neo4j-db
          property: user
      - key: NEO4J_PASSWORD
        fromDatabase:
          name: neo4j-db
          property: password
      - key: API_TOKEN
        generateValue: true
      - key: SERVER_URL
        fromService:
          type: web
          name: asha-api
          envVarKey: RENDER_EXTERNAL_URL

  # Streamlit Frontend Service
  - type: web
    name: asha-frontend
    env: python
    buildCommand: pip install -r requirements-frontend.txt
    startCommand: streamlit run streamlit_app.py
    envVars:
      - key: API_URL
        fromService:
          type: web
          name: asha-api
          envVarKey: RENDER_EXTERNAL_URL

databases:
  - name: neo4j-db
    databaseType: neo4j